### PR TITLE
Laravel 5.6 Shift

### PR DESCRIPTION
**Pull request by MarcyLina**
This pull request includes the changes for upgrading to Laravel 5.6. Feel free to commit any additional changes to the `shift-43330` branch.

**Before merging**, you need to:

- Checkout the `shift-43330` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.6
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by MarcyLina** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by MarcyLina** [comment]
:warning: Looks like you already have a `config/hashing.php`. Laravel 5.6 added this as a core config file. You should add the [5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/config/hashing.php) to your application and merge your customizations.

**Comment by MarcyLina** [comment]
:warning: Looks like you already have a `config/logging.php`. Laravel 5.6 added this as a core config file. You should add the [5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/config/logging.php) to your application and merge your customizations.

**Comment by MarcyLina** [comment]
:information_source: Laravel 5.6 introduced a _logging_ configuration file. You should ensure the `log` and `log_level` settings previously in the `config/app.php` are now set in `config/logging.php`.

**Comment by MarcyLina** [comment]
:warning: Since you are upgrading from an older version of Laravel, Shift defaulted your customized configuration files to improve the automation in your next Shift. This was done in [a separate commit](https://github.com/tighten/saasaas/pull/6/commits/515bbd103ae4edc9cc0a460f7663479fd7daa89d?w=1) so you may easily reference the changes and backfill your customizations once you are done _Shifting_. Future Shifts (Laravel 6+) will preserve your true customizations by merging them back in with the defaults.

- [ ] config/auth.php

**Comment by MarcyLina** [comment]
:information_source: Laravel 5.6 recommends using the [_Hash_ facade](https://laravel.com/docs/5.6/hashing) instead of the `bcrypt` function directly as it provides greater flexibility for additional hashing algorithms and leverages the new `hashing.php` configuration.

Since Laravel uses the `bcrypt` algorithm by default, Shift [converted your instances](https://github.com/tighten/saasaas/pull/6/commits/c07fb265742899de2640395ddb60c31296ea3455?w=1) of `bcrypt()` to `Hash::make()`.

**Comment by MarcyLina** [comment]
:x: Laravel 5.6 has a dependency for `php` of `^7.1.3`. You have a modified dependency for `php` in your `composer.json`. You should review your dependency and ensure it meets the new version requirement.

**Comment by MarcyLina** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 4.0. If you are directly interacting with any Symfony components, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/4.0/CHANGELOG-4.0.md) for additional changes.

**Comment by MarcyLina** [comment]
:information_source: The `optimize` command was deprecated in Laravel 5.5 and removed in Laravel 5.6. However, it is re-added in Laravel 5.7. If you are using this command, it may be temporarily unavailable.

**Comment by MarcyLina** [comment]
:information_source: In Laravel 5.6, Blade will double encode special characters by default. If you would like to maintain the previous behavior of preventing double encoding, you may add `Blade::withoutDoubleEncoding()` to your AppServiceProvider `boot` method.

**Comment by MarcyLina** [comment]
:information_source: Laravel 5.6 uses Bootstrap 4 by default. Shift did not update your front-end resources or dependencies as this could impact your UI. If you are using Bootstrap and wish to continue using Bootstrap 3, you should add `Paginator::useBootstrapThree()` to your _AppServiceProvider_ `boot` method.

**Comment by MarcyLina** [comment]
:warning: Laravel 5.6 has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest LTS version (Laravel 6.x) or latest stable version (Laravel 8.x). For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Comment by mattstauffer** [comment]
Looks good to me!

**Pull request merged**
