### PR TITLE
Laravel 5.6 Shift

### PR DESCRIPTION
**Pull request by mattstauffer**
This pull request includes the changes for upgrading to Laravel 5.6. Feel free to commit any additional changes to the `shift-48521` branch.

**Before merging**, you need to:

- Checkout the `shift-48521` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 5.6
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by mattstauffer** [comment]
:information_source: Shift noticed you have additional namespaces in your application. You may use the [Consolidate Namespaces Shift](https://laravelshift.com/laravel-consolidate-custom-namespaces) to simplify your namespaces into the default Laravel `App` namespace.

**Comment by mattstauffer** [comment]
:x: Looks like you already have an `app/Http/Middleware/CheckForMaintenanceMode.php`. Laravel 5.6 includes the `CheckForMaintenanceMode` middleware within your application. If this is a custom class, you should rename yours and copy the [Laravel 5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/app/Http/Middleware/CheckForMaintenanceMode.php) into your app. Otherwise, you should compare yours against the [Laravel 5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/app/Http/Middleware/CheckForMaintenanceMode.php) and merge any changes.

**Comment by mattstauffer** [comment]
:x: Laravel 5.6 updated the binding for `CheckForMaintenanceMode` as well as added a new middleware named `cache.headers`. Shift was not able to automate these changes. You will need to compare your `app/Http/Kernel.php` against the [Laravel 5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/app/Http/Kernel.php) and merge these changes manually.

**Comment by mattstauffer** [comment]
:warning: Shift could not upgrade the `TrustProxies` *Middleware* since it differed from the default Laravel version. You should compare your file to the [5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/app/Http/Middleware/TrustProxies.php) and upgrade your application accordingly.

**Comment by mattstauffer** [comment]
:information_source: Laravel 5.6 added a new `BCRYPT_ROUNDS` environment variable it sets during testing to improve performance. You may add the set this in your `phpunit.xml` by adding the following configuration:

```php
<env name="BCRYPT_ROUNDS" value="4"/>
```

**Comment by mattstauffer** [comment]
:warning: Shift could not upgrade the following files since they differed from the default Laravel version. You should compare these application files against the [default Laravel 5.6 versions](https://github.com/laravel-shift/laravel-5.6/) and merge any changes:

- [ ] app/Http/Controllers/Auth/RegisterController.php

**Comment by mattstauffer** [comment]
:warning: Looks like you already have a `config/hashing.php`. Laravel 5.6 added this as a core config file. You should add the [5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/config/hashing.php) to your application and merge your customizations.

**Comment by mattstauffer** [comment]
:warning: Looks like you already have a `config/logging.php`. Laravel 5.6 added this as a core config file. You should add the [5.6 version](https://github.com/laravel-shift/laravel-5.6/blob/master/config/logging.php) to your application and merge your customizations.

**Comment by mattstauffer** [comment]
:information_source: Laravel 5.6 introduced a _logging_ configuration file. You should ensure the `log` and `log_level` settings previously in the `config/app.php` are now set in `config/logging.php`.

**Comment by mattstauffer** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 4.0. If you are directly interacting with any Symfony components, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/4.0/CHANGELOG-4.0.md) for additional changes.

**Comment by mattstauffer** [comment]
:information_source: The `optimize` command was deprecated in Laravel 5.5 and removed in Laravel 5.6. However, it is re-added in Laravel 5.7. If you are using this command, it may be temporarily unavailable.

**Comment by mattstauffer** [comment]
:information_source: In Laravel 5.6, Blade will double encode special characters by default. If you would like to maintain the previous behavior of preventing double encoding, you may add `Blade::withoutDoubleEncoding()` to your AppServiceProvider `boot` method.

**Comment by mattstauffer** [comment]
:information_source: Laravel 5.6 uses Bootstrap 4 by default. Shift did not update your front-end resources or dependencies as this could impact your UI. If you are using Bootstrap and wish to continue using Bootstrap 3, you should add `Paginator::useBootstrapThree()` to your _AppServiceProvider_ `boot` method.

**Comment by mattstauffer** [comment]
:warning: Laravel 5.6 has reached [end of life](https://laravelversions.com/). It no longer receives bug fixes or security updates. Shift recommends continuing to upgrade to the latest LTS version (Laravel 6.x) or latest stable version (Laravel 8.x). For tips on running multiple Shifts effectively, watch [upgrading old Laravel applications](https://laravelshift.com/videos/upgrading-old-laravel-applications).

**Comment by anna-youngyeun** [comment]
Shift to 5.6 was completed.  Closing this PR & moving to 5.7 next.

**Pull request closed without merging**
